### ISSUE TITLE
Error when loading a saved committor simulation storage file 

### ISSUE THREAD

**Issue by mayank-agr** [openpathsampling/openpathsampling#922]
I am getting errors when I load any saved .nc file after committor simulation. It works perfectly after a TPS simulation but never works after a committor simulation. Can anyone please help me with this error?

I appreciate it
Thanks,
Mayank

The error I am getting is "ValueError: Value is too big!"  and the full error is as follows:

```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-9c6cf6fe1e43> in <module>
----> 1 output_storage = paths.AnalysisStorage("final_committor_113_500each.nc")

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/storage/storage.py in __init__(self, filename, caching_mode)
    499 
    500         # Let's go caching
--> 501         AnalysisStorage.cache_for_analysis(self)
    502 
    503     @staticmethod

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/storage/storage.py in cache_for_analysis(storage)
    532             store = getattr(storage, store_name)
    533             with AnalysisStorage.CacheTimer('Cache all objects', store):
--> 534                 store.cache_all()
    535 
    536     class CacheTimer(object):

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/stores/variable.py in cache_all(self, part)
     99             data = zip(*[
    100                 self.vars[var][part]
--> 101                 for var in self.var_names
    102             ])
    103 

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/stores/variable.py in <listcomp>(.0)
     99             data = zip(*[
    100                 self.vars[var][part]
--> 101                 for var in self.var_names
    102             ])
    103 

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/netcdfplus.py in __getitem__(self, key)
    123             # print(self.variable[key])
    124             # print(type(self.variable[key]))
--> 125             return self.getter(self.variable[key])
    126 
    127         def __getattr__(self, item):

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/netcdfplus.py in <lambda>(v)
    904                 None if w[0] == '-' else store.load(int(UUID(w)))
    905                 for w in v
--> 906             ] if get_numpy_iterable(v) else \
    907                 None if v[0] == '-' else store.load(int(UUID(v)))
    908 

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/netcdfplus.py in <listcomp>(.0)
    903             getter = lambda v: [
    904                 None if w[0] == '-' else store.load(int(UUID(w)))
--> 905                 for w in v
    906             ] if get_numpy_iterable(v) else \
    907                 None if v[0] == '-' else store.load(int(UUID(v)))

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/stores/named.py in load(self, idx)
    271                 'This should never happen!')
    272         else:
--> 273             obj = self._load(n_idx)
    274 
    275         if self._log_debug:

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/storage/stores/pathsimulator.py in _load(self, idx)
     13 
     14     def _load(self, idx):
---> 15         obj = super(PathSimulatorStore, self)._load(idx)
     16         if hasattr(obj, 'storage'):
     17             obj.storage = self.storage

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/stores/object.py in _load(self, idx)
    442 
    443     def _load(self, idx):
--> 444         obj = self.vars['json'][idx]
    445         return obj
    446 

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/netcdfplus.py in __getitem__(self, key)
    123             # print(self.variable[key])
    124             # print(type(self.variable[key]))
--> 125             return self.getter(self.variable[key])
    126 
    127         def __getattr__(self, item):

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/netcdfplus.py in <lambda>(v)
    894         elif var_type == 'jsonobj':
    895             setter = lambda v: self.simplifier.to_json_object(v)
--> 896             getter = lambda v: self.simplifier.from_json(v)
    897 
    898         elif var_type == 'json':

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/dictify.py in from_json(self, json_string)
    584 
    585     def from_json(self, json_string):
--> 586         simplified = ujson.loads(json_string)
    587         return self.build(simplified)
    588 

ValueError: Value is too big!
```

**Comment by dwhswenson** [comment]
Thanks for the report, @mayank-agr.

A few initial thoughts:

1. In principle, there's no reason storage of committor sims would be different from TPS sims. However, there might be some other factor that is related to other differences in these simulations.
2. The error is actually coming from [`ujson`](https://github.com/ultrajson/ultrajson), which is a package we use to convert objects to bytes that we can save on disk. I know that they have recently released a new version, with some major changes, so I wonder if it is possible that you ran the simulation with one version and loaded with another. See also #917 and #921, which fixed some OPS compatibility problems. If this is the case, you might try (1) using the master branch of OPS (those PRs are coming in the 1.3.0 release, sometime soon); (2) downgrading to ujson < 3. (@sroet @hejung, did either of you see an error like this?)
3. I believe error is supposed to indicate that the you're trying to convert an string to an int, but the string represents an int that is too large for. But since we also use `ujson` to serialize, I would expect they would have complained going that way, too.
4. You're using `AnalysisStorage`, and the error occurs during caching specific to `AnalysisStorage`. You might try using a normal `Storage` (with `mode='r'`) instead -- this is slower for some things, but maybe not for a committor analysis. (I think the main things it does is to cache CV results and details of what happened during a move.) However, the error might still occur while actually performing the analysis.
5. It's hard to know more without debugging some. One easy bit of debugging would be to see exactly what string is causing the error. If you're in a Jupyter notebook, just add `%pdb` in the cell before opening the storage. When the error occurs, you'll be dropped into the [`pdb`](https://docs.python.org/3/library/pdb.html) debugger (which is very similar to gdb, if you've ever used that on C code). Assuming it shows the same error (on line 586), you can just type `json_string` and it will print the contents of that variable. (Type `quit` after that or that notebook cell will remain active until you kill the kernel.)

In a worst case scenario, we can probably find a monkey patch that can get this to work. As I recall, we switched to `ujson` entirely for speed, not for any functionality -- in fact, I think it has *less* functionality than the Python standard library `json`. 

However, this is unfortunately a part of the code that I didn't write, and @jhprinz (who wrote it) doesn't have the time available to maintain it. For what it's worth, I'm working on a full replacement to the storage subsystem, which I hope will be both faster and more maintainable by others.

(edited OP for pytb formatting)

**Comment by sroet** [comment]
> (@sroet @hejung, did either of you see an error like this?)

I have not issues other than the one fixed in those PRs, which came up in the test suite. But, I haven't run any production with this Openpathsampling storage backend, recently.

**Comment by mayank-agr** [comment]
Thanks for the quick reply David. I tried everything you suggested (modified the code as suggested in #917 and #921) but still getting the same error. There is one thing I am doing different - using lammps as external engine. Do you think that might have caused the problem?

Also, it is weird that I can load a saved simulation after TPS, only the saved file after committor analysis is giving the problem. 

the additional error after adding %pdb while loading the saved file is as follows:

> /gpfs/data/ap31/magrawa3/softwares/py3_modules/git/openpathsampling/openpathsampling/netcdfplus/dictify.py(590)from_json()
    588 
    589     def from_json(self, json_string):
--> 590         simplified = ujson.loads(json_string)
    591         return self.build(simplified)
    592 


Thanks,
Mayank

**Comment by hejung** [comment]
< 3. (@sroet @hejung, did either of you see an error like this?)
I have also only seen the fixed issue. And for me that error appeared already on saving (the toy engine).
But I have not used an AnalysisStorage for a long time. I just use a readonly storage for analysis.

**Comment by dwhswenson** [comment]
@mayank-agr : When you run it with the `%pdb` magic, the error should drop you into a debugging shell (in the output cell, with the prompt `ipdb>`).  Within that shell, you can inspect the variables. The main question I have is, what is the content of the `json_string` variable at that point? You can get this by typing `json_string` in the debug shell. (Note that you'll eventually have to type `quit` in the debug shell to get control back in your normal notebook cells.)

Additionally, just to confirm: you also got an error when loading as `Storage` instead of `AnalysisStorage`? Could you post the traceback (full error) for that? The original error you reported is in something specific in `AnalysisStorage`, which is why I thought regular `Storage` might work.

> There is one thing I am doing different - using lammps as external engine. Do you think that might have caused the problem?

I don't think so, although it's not impossible. It looks like the error is because some object has a value that is outside the bounds of what `ujson` can handle (probably an integer value that is too large -- `ujson` uses C numeric types, which have more restrictions than Python numeric types). Most information about the LAMMPS engine is stored as a string, so there should be no attempt to convert it to an int. But getting the value of `json_string` is the best way to get information about the culprit.

**Comment by mayank-agr** [comment]
Hi David, 

I am able to load the .nc file using regular Storage command. In that case, I am getting an error with the following line:

shooting_pts = [analyzer.step_key(step) for step in storage.steps]

The error is the following:

```
Automatic pdb calling has been turned ON

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-c4300a496bf7> in <module>
      1 get_ipython().run_line_magic('pdb', '')
      2 # the shooting point snapshot for each
----> 3 shooting_pts = [analyzer.step_key(step) for step in output_storage.steps]

<ipython-input-7-c4300a496bf7> in <listcomp>(.0)
      1 get_ipython().run_line_magic('pdb', '')
      2 # the shooting point snapshot for each
----> 3 shooting_pts = [analyzer.step_key(step) for step in output_storage.steps]

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/stores/object.py in __iter__(self)
    336         # we want to iterator in the order object were saved!
    337         for uuid in self.index._list:
--> 338             yield self.load(uuid)
    339 
    340     def __len__(self):

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/stores/object.py in load(self, idx)
    766                 'This should never happen!')
    767         else:
--> 768             obj = self._load(n_idx)
    769 
    770         if self._log_debug:

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/stores/variable.py in _load(self, idx)
     56     def _load(self, idx):
     57         # kwargs = {var: self.vars[var][idx] for var in self.var_names}
---> 58         args = [self.vars[var][idx] for var in self.var_names]
     59         return self.content_class(*args)
     60 

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/stores/variable.py in <listcomp>(.0)
     56     def _load(self, idx):
     57         # kwargs = {var: self.vars[var][idx] for var in self.var_names}
---> 58         args = [self.vars[var][idx] for var in self.var_names]
     59         return self.content_class(*args)
     60 

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/netcdfplus.py in __getitem__(self, key)
    123             # print(self.variable[key])
    124             # print(type(self.variable[key]))
--> 125             return self.getter(self.variable[key])
    126 
    127         def __getattr__(self, item):

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/netcdfplus.py in <lambda>(v)
    905                 for w in v
    906             ] if get_numpy_iterable(v) else \
--> 907                 None if v[0] == '-' else store.load(int(UUID(v)))
    908 
    909             setter = lambda v: \

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/stores/named.py in load(self, idx)
    271                 'This should never happen!')
    272         else:
--> 273             obj = self._load(n_idx)
    274 
    275         if self._log_debug:

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/storage/stores/pathsimulator.py in _load(self, idx)
     13 
     14     def _load(self, idx):
---> 15         obj = super(PathSimulatorStore, self)._load(idx)
     16         if hasattr(obj, 'storage'):
     17             obj.storage = self.storage

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/stores/object.py in _load(self, idx)
    442 
    443     def _load(self, idx):
--> 444         obj = self.vars['json'][idx]
    445         return obj
    446 

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/netcdfplus.py in __getitem__(self, key)
    123             # print(self.variable[key])
    124             # print(type(self.variable[key]))
--> 125             return self.getter(self.variable[key])
    126 
    127         def __getattr__(self, item):

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/netcdfplus.py in <lambda>(v)
    894         elif var_type == 'jsonobj':
    895             setter = lambda v: self.simplifier.to_json_object(v)
--> 896             getter = lambda v: self.simplifier.from_json(v)
    897 
    898         elif var_type == 'json':

~/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/dictify.py in from_json(self, json_string)
    588 
    589     def from_json(self, json_string):
--> 590         simplified = ujson.loads(json_string)
    591         return self.build(simplified)
    592 

ValueError: Value is too big!

> /users/magrawa3/data/magrawa3/softwares/miniconda3/envs/env_py3.6/lib/python3.6/site-packages/openpathsampling/netcdfplus/dictify.py(590)from_json()
    588 
    589     def from_json(self, json_string):
--> 590         simplified = ujson.loads(json_string)
    591         return self.build(simplified)
    592 

ipdb>  json_string

'{"_cls":"CommittorSimulation","_dict":{"engine":{"_hex_uuid":"0x83b92052c48611eaaf4400000000000c","_store":"engines"},"initial_snapshots":[{"_hex_uuid":"0x83b92052c48611eaaf440000000150aa","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000001425f","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000006bfe","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000a866","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000c2bb","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000cec8","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000081c8","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000007339","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000001447f","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000ed1c","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000dfa5","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000002e09","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000d197","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000013fb","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000116c5","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000007478","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000001f49","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000000ac","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000001436e","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000109b7","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000d674","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000035c4","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000ac73","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000016e43","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000044d0","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000000703","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000348b","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000015a3b","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000081de","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000071fd","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000671b","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000014e8d","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000c7c2","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000165c3","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000099de","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000039a9","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000011028","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000000db8","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000968f","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000003744","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000d529","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000006be8","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000106e3","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000015cba","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000007802","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000002cd4","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000059e3","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000d16f","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000008eed","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000002f15","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000006a32","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000116d9","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000959d","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000b880","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000a87c","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000c609","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000002e1d","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000005d56","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000014803","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000feea","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000059cf","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000044ba","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000015dde","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000009b5a","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000138dd","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000015522","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000cca6","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000171ee","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000002f29","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000fa21","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000d78d","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000001d64","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000015b96","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000d7dd","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000006e93","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000f1af","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000066df","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000165ff","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000237f","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000f8e0","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000afcc","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000080a1","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000efaa","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000ee3c","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000164b2","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000094ba","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000ad78","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000ef94","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000015a27","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000cd9d","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000c4fe","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000181c","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000bde8","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000150c0","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000014d6b","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000152ba","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000e3f1","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000001493d","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000001bbf","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000138f1","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000fe02","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000ee26","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000003b34","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000006ea7","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000dab2","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000be40","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000000d551","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000016d79","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000014694","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf4400000001672b","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000015538","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf440000000158fd","_store":"snapshots"},{"_hex_uuid":"0x83b92052c48611eaaf44000000015693","_store":"snapshots"}],"randomizer":{"_cls":"RandomVelocities","_obj_uuid":"41019b60-c6c8-11ea-9b60-00000000a5ac","_dict":{"beta":{"_value":241432105718676720000.0,"_units":{"joule":-1}},"engine":{"_hex_uuid":"0x83b92052c48611eaaf4400000000000c","_store":"engines"},"subset_mask":null}},"starting_ensemble":{"_hex_uuid":"0x41019b60c6c811ea9b6000000000a5fe","_store":"ensembles"},"forward_ensemble":{"_hex_uuid":"0x41019b60c6c811ea9b6000000000a5ec","_store":"ensembles"},"backward_ensemble":{"_hex_uuid":"0x41019b60c6c811ea9b6000000000a5f6","_store":"ensembles"},"mover":{"_hex_uuid":"0x41019b60c6c811ea9b6000000000a60a","_store":"pathmovers"},"states":[{"_hex_uuid":"0x83b92052c48611eaaf44000000000024","_store":"volumes"},{"_hex_uuid":"0x83b92052c48611eaaf44000000000026","_store":"volumes"}],"direction":null}}'
```

Please let me know what you think.

**Comment by dwhswenson** [comment]
Thanks, the `json_string` explains it all. The problem is that, somehow, the string value for `beta` (from the velocity randomizer you use in the committor) is stored as `241432105718676720000.0`, which looks like it is trying to have some additional precision (because those zeros at the end are explicit). It should be written as `2.414321057186767e+20`. This also explains you why only got this with the committor (only place where you have this `beta`, assuming your TPS was one-way shooting) and why you got it every time with the committor. So this is *what* went wrong; I have no idea *why* that went wrong. My best guess is a mix of different software versions.

Here's an IPython session to illustrate the problem. The `beta_str` is a substring of the `json_string` you found.

```
In [1]: import json
   ...: import ujson
   ...:
   ...:

In [2]: beta_str = '{"_value":241432105718676720000.0,"_units":{"joule":-1}}'

In [3]: ujson.loads(beta_str)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-de975e582a93> in <module>
----> 1 ujson.loads(beta_str)

ValueError: Value is too big!

In [4]: dct = json.loads(beta_str)
   ...: dct
   ...:
   ...:
Out[4]: {'_value': 2.4143210571867672e+20, '_units': {'joule': -1}}

In [5]: ujson.dumps(dct)
Out[5]: '{"_value":2.414321057186767e+20,"_units":{"joule":-1}}'

In [6]: ujson.loads(ujson.dumps(dct))
Out[6]: {'_value': 2.4143210571867672e+20, '_units': {'joule': -1}}
```

Python's `json` standard library seems to be able to handle it. So I think the best try for a fix is to monkey-patch `ujson` with the standard `json` library. I think that all you need in order to do that would be to start your analysis file with:

```python
import openpathsampling as paths
import json
paths.netcdfplus.dictify.ujson = json
```

I'm not 100% sure that this won't have any other weird side effects, although I think it will be okay. As I recall, `ujson` focuses on only supporting the core JSON standard, without some of the extensions that, for example, the `json` module can support. So (IIRC) we added some work-arounds for special Python values (such as `float(inf)`) that are outside `ujson`'s support. I don't think there wsa anything `ujson` did that `json` couldn't. However, it was much faster, so this will slow down the loading process. Definitely use regular `Storage` instead of `AnalysisStorage` unless you'll need the extra stuff `AnalysisStorage` caches. As I recall,that's mainly values of CVs for all snapshots and the full list of move changes (used for analysis of move acceptance, etc.), neither of which are probably essential when analyzing a committor simulation.

**Comment by mayank-agr** [comment]
Hi David,

It is working perfectly fine now. I am even able to open the old files and do the analysis. Thanks a lot for your help, I appreciate it. 

Best,
Mayank

**Comment by hejung** [comment]
@dwhswenson I was able to reproduce the error, that is I ran into it today.
For me the issue was that I used the temperature from the openMM-intergrator (which has units) to calculate beta (`beta = 1. / (integrator.getTemperature() * unit.BOLTZMANN_CONSTANT_kB)` ). Using this beta as beta for the `paths.RandomVelocities` shooting point modificator results in the known error. The relevant json_string of the modifier is:
```python
"modifier":{"_cls":"RandomVelocities","_obj_uuid":"d3efc2f4-f0e8-11ea-8212-000000000254","_dict":{"subset_mask":null,"beta":{"_value":241432105718676720000.0,"_units":{"joule":-1}}
```
This had worked previously and I am not sure yet what changed, i.e. beta should have had units of 1/J all the time.
However I am sure that the problem happens somewhere in the saving.
If I look at modifier.to_dict() of the freshly created `paths.RandomVelocities` I get the right values, i.e. floats in scientific notation.
```python
{'subset_mask': None,
 'beta': Quantity(value=2.4143210571867672e+20, unit=/joule),
 'engine': <openpathsampling.engines.openmm.engine.OpenMMEngine at 0x7fddc1ffcc10>}
```
If I put the relevant part of that string through simplify it still looks good:
```python
from simtk import unit
from openpathsampling.netcdfplus.dictify import ObjectJSON
json_str = {'subset_mask': None,
                  'beta': unit.Quantity(value=2.4143210571867672e+20, unit=1/unit.joule)}
simple_pickler = ObjectJSON()
simple_pickler.simplify(json_str)
# returns: {'subset_mask': None,  'beta': {'_value': 2.4143210571867672e+20, '_units': {'joule': -1}}}
```
And this is where I got lost.
Questions @dwhswenson  :
1. Is there anything else that happens when saving that I missed here? I.e. anything more happening than calling `to_dict()`, replacing objects in the dict that are already in the store with their id and finally calling simplify on the dictionary?
2. `ObjectJSON.simplify()` takes a unit_system. I left this at None because that returns me the units unchanged as [1/J] (which they have in the storage too). Is that the expected value for openMM simulations? 
3. The error seems to happen only with ujson >= 3 and openMM, i.e. ujson >= 3 and storing simtk.unit.Quantities.

**Comment by hejung** [comment]
Ah! I found it. It is an error in ujson:
ujson v 1.35:
```python
import ujson
dct = {'subset_mask': None,
          'beta': {'_value': 2.4143210571867672e+20, '_units': {'joule': -1}}}
json_str = ujson.dumps(dct)
# now json_str = '{"subset_mask":null,"beta":{"_value":2.414321057186767e+20,"_units":{"joule":-1}}}'
dct_loaded = ujson.loads(json_str)
# and dct_loaded is exactly dct
```
And for ujson v 3.0.0:
```python
import ujson
dct = {'subset_mask': None,
          'beta': {'_value': 2.4143210571867672e+20, '_units': {'joule': -1}}}
json_str = ujson.dumps(dct)
# now json_str = '{"subset_mask":null,"beta":{"_value":241432105718676720000.0,"_units":{"joule":-1}}}'
dct_loaded = ujson.loads(json_str)  # raises the known error
```
So I guess we should require ujson < 3? (I haven't checked yet in which version exactly the problem was introduced, I only tested 1.35 and 3.0 since they wehere installed in two different conda envs.)

**Comment by dwhswenson** [comment]
Ugh... after you and Sander already made a bunch of PRs to give us ujson 3 compatibility.... but those PRs work with ujson 2, right?

I think `ujson < 3` may be the solution. If people don't want to downgrade, monkey-patching `paths.netcdfplus.dictify.ujson = json` will work. I'm working on a replacement for the entirety of the netcdfplus subsystem. It won't require ujson (and also should be faster than netcdfplus).

**Comment by dwhswenson** [comment]
The underlying issue in ujson has been fixed (round-tripping problems fixed as a side effect of https://github.com/ultrajson/ultrajson/pull/443, but the more fundamental error was fixed by https://github.com/ultrajson/ultrajson/pull/442). So we can relax the pin of ujson when it gets its next release.
